In [ ]:
# https://python-course.eu/machine-learning/train-and-test-sets-by-splitting-learn-and-test-data.php

In [2]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
indices = np.random.permutation(len(iris.data))
indices

array([ 14, 143,  45, 109, 145,  51, 138,  92,   7,  29,  83,  58,  93,
        23, 111,  25,  72,  41, 117,  28,  16,  86, 102, 144,   2, 139,
         3,  27,  30, 134, 136,  95, 146,  59,  21,  37, 122,  78,  20,
        66, 118,  22,  76,   4,  35,  94,  80, 110,  81,  98, 132,  62,
        74,   8,  89,  44,  70, 103,   9,  26, 148,  73,  36, 140,  57,
       119,  11, 114,  64,  13, 149,  90, 131, 137,  82,  77,   0, 124,
         1,  53, 133, 142, 108,   5, 105,  52, 121,  32,  18,  10,  55,
        96,  47, 112, 113,  61, 130,  38, 116, 104,  12, 101, 141, 120,
        17, 128,  46,  19,  91,  43, 115,  42,  71,  15, 126, 125,  67,
        39,  68,  63, 127, 147,  24, 135,  97,  88,  40, 107,  31,  49,
       129,   6,  99,  33,  48,  87,  65,  79, 100,  75,  54,  69, 123,
        60,  50,  34, 106,  85,  84,  56])

In [4]:
n_test_samples = 12
learnset_data = iris.data[indices[:-n_test_samples]]
learnset_labels = iris.target[indices[:-n_test_samples]]
testset_data = iris.data[indices[-n_test_samples:]]
testset_labels = iris.target[indices[-n_test_samples:]]
print(learnset_data[:4], learnset_labels[:4])
print(testset_data[:4], testset_labels[:4])

[[5.8 4.  1.2 0.2]
 [6.8 3.2 5.9 2.3]
 [4.8 3.  1.4 0.3]
 [7.2 3.6 6.1 2.5]] [0 2 0 2]
[[6.3 3.3 6.  2.5]
 [6.6 3.  4.4 1.4]
 [6.5 2.8 4.6 1.5]
 [5.6 2.5 3.9 1.1]] [2 1 1 1]
