In [ ]:
# https://python-course.eu/machine-learning/train-and-test-sets-by-splitting-learn-and-test-data.php

In [2]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
indices = np.random.permutation(len(iris.data))
indices

array([ 14, 143,  45, 109, 145,  51, 138,  92,   7,  29,  83,  58,  93,
        23, 111,  25,  72,  41, 117,  28,  16,  86, 102, 144,   2, 139,
         3,  27,  30, 134, 136,  95, 146,  59,  21,  37, 122,  78,  20,
        66, 118,  22,  76,   4,  35,  94,  80, 110,  81,  98, 132,  62,
        74,   8,  89,  44,  70, 103,   9,  26, 148,  73,  36, 140,  57,
       119,  11, 114,  64,  13, 149,  90, 131, 137,  82,  77,   0, 124,
         1,  53, 133, 142, 108,   5, 105,  52, 121,  32,  18,  10,  55,
        96,  47, 112, 113,  61, 130,  38, 116, 104,  12, 101, 141, 120,
        17, 128,  46,  19,  91,  43, 115,  42,  71,  15, 126, 125,  67,
        39,  68,  63, 127, 147,  24, 135,  97,  88,  40, 107,  31,  49,
       129,   6,  99,  33,  48,  87,  65,  79, 100,  75,  54,  69, 123,
        60,  50,  34, 106,  85,  84,  56])

In [4]:
n_test_samples = 12
learnset_data = iris.data[indices[:-n_test_samples]]
learnset_labels = iris.target[indices[:-n_test_samples]]
testset_data = iris.data[indices[-n_test_samples:]]
testset_labels = iris.target[indices[-n_test_samples:]]
print(learnset_data[:4], learnset_labels[:4])
print(testset_data[:4], testset_labels[:4])

[[5.8 4.  1.2 0.2]
 [6.8 3.2 5.9 2.3]
 [4.8 3.  1.4 0.3]
 [7.2 3.6 6.1 2.5]] [0 2 0 2]
[[6.3 3.3 6.  2.5]
 [6.6 3.  4.4 1.4]
 [6.5 2.8 4.6 1.5]
 [5.6 2.5 3.9 1.1]] [2 1 1 1]


In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
data, labels = iris.data, iris.target

res = train_test_split(data, labels, 
                       train_size=0.8,
                       test_size=0.2,
                       random_state=42)
train_data, test_data, train_labels, test_labels = res    

n = 7
print(f"The first {n} data sets:")
print(test_data[:7])
print(f"The corresponding {n} labels:")
print(test_labels[:7])

The first 7 data sets:
[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]]
The corresponding 7 labels:
[1 0 2 1 1 0 1]


In [6]:
import numpy as np
print('All:', np.bincount(labels) / float(len(labels)) * 100.0)
print('Training:', np.bincount(train_labels) / float(len(train_labels)) * 100.0)
print('Test:', np.bincount(test_labels) / float(len(test_labels)) * 100.0)

All: [33.33333333 33.33333333 33.33333333]
Training: [33.33333333 34.16666667 32.5       ]
Test: [33.33333333 30.         36.66666667]


In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
data, labels = iris.data, iris.target

res = train_test_split(data, labels, 
                       train_size=0.8,
                       test_size=0.2,
                       random_state=42,
                       stratify=labels)
train_data, test_data, train_labels, test_labels = res 

print('All:', np.bincount(labels) / float(len(labels)) * 100.0)
print('Training:', np.bincount(train_labels) / float(len(train_labels)) * 100.0)
print('Test:', np.bincount(test_labels) / float(len(test_labels)) * 100.0)

All: [33.33333333 33.33333333 33.33333333]
Training: [33.33333333 33.33333333 33.33333333]
Test: [33.33333333 33.33333333 33.33333333]


In [8]:
content = np.loadtxt("data/strange_flowers.txt", delimiter=" ")
data = content[:, :-1]    # cut of the target column
labels = content[:, -1]
labels.dtype
labels.shape

FileNotFoundError: data/strange_flowers.txt not found.