In [14]:
# https://python-course.eu/numerical-programming/reading-and-writing-data-files-ndarrays.php

In [15]:
import numpy as np

x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]], np.int32)

np.savetxt("./data/test.txt", x)

In [16]:
np.savetxt("./data/test2.txt", x, fmt="%2.3f", delimiter=",")
np.savetxt("./data/test3.txt", x, fmt="%04d", delimiter=" :-) ")

In [17]:
y = np.loadtxt("./data/test.txt")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [18]:
y = np.loadtxt("./data/test2.txt", delimiter=",")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [19]:
y = np.loadtxt("./data/test3.txt", delimiter=" :-) ")
print(y)

TypeError: Text reading control character must be a single unicode character or None; but got: ' :-) '