In [ ]:
# https://python-course.eu/numerical-programming/reading-and-writing-data-files-ndarrays.php

In [1]:
import numpy as np

x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]], np.int32)

np.savetxt("./data/test.txt", x)

In [ ]:
np.savetxt("./data/test2.txt", x, fmt="%2.3f", delimiter=",")
np.savetxt("./data/test3.txt", x, fmt="%04d", delimiter=" :-) ")

In [ ]:
y = np.loadtxt("./data/test.txt")
print(y)

In [ ]:
y = np.loadtxt("./data/test2.txt", delimiter=",")
print(y)

In [ ]:
y = np.loadtxt("./data/test3.txt", delimiter=" :-) ")
print(y)

In [2]:
dt = np.dtype([('time', [('min', int), ('sec', int)]),
               ('temp', float)])
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10
x['temp'] = 98.25
print(x)

fh = open("test6.txt", "bw")
x.tofile(fh)

[((10, 0), 98.25)]


In [4]:
fh = open("./data/test.txt", "rb")

np.fromfile(fh, dtype=dt)

array([((3472328296227679793, 3472328296227680304), 1.39642638e-076),
       ((3472328296227549728, 3472328296227680304), 1.18295070e-076),
       ((3472328296194318384, 3472328296227680304), 1.21089429e-099),
       ((3472328287702364208, 3472328296227680304), 2.62395837e+179),
       ((3472326118410825771, 3472328296227680304), 1.39804329e-076),
       ((3471771874624547685, 3472328296227680304), 1.39804329e-076),
       ((3330141651546629424, 3472328296227680304), 1.39804329e-076),
       ((4044285448823320624, 3472328296227680302), 1.39804329e-076),
       ((2319406771035189296, 3472328296227679801), 1.39804329e-076)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [6]:
import numpy as np
import os

# platform dependent: difference between Linux and Windows
#data = np.arange(50, dtype=np.int)

data = np.arange(50, dtype=np.int32)
data.tofile("./data/test4.txt")

fh = open("./data/test4.txt", "rb")
# 4 * 32 = 128
fh.seek(128, os.SEEK_SET)

x = np.fromfile(fh, dtype=np.int32)
print(x)

[32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
import numpy as np

print(x)

from tempfile import TemporaryFile

outfile = TemporaryFile()

x = np.arange(10)
np.save(outfile, x)

outfile.seek(0) # Only needed here to simulate closing & reopening file
np.load(outfile)

[32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])