In [ ]:
# https://python-course.eu/numerical-programming/matrix-arithmetics-under-numpy-and-python.php

In [1]:
import numpy as np

x = np.array([1, 5, 2])
y = np.array([7, 4, 1])
x + y

array([8, 9, 3])

In [2]:
y%x

array([0, 4, 1])

In [2]:
x = np.array([1, 2, 3])
y = np.array([-7, 8, 9])
np.dot(x, y)

36

In [3]:
dot = np.dot(x ,y)
x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())
cos_angle = dot / x_modulus / y_modulus # cosine of angle between x and y
angle = np.arccos(cos_angle)
angle

0.808233789010825

In [5]:
angle * 180/ np.pi # angle in degrees

46.308384970187326

In [6]:
import numpy as np
NumPersons = np.array([[100, 175, 210],
                       [90, 160, 150],
                       [200, 50, 100],
                       [120, 0, 310]])
Price_per_100_g = np.array([2.98, 3.90, 1.99])
Price_in_Cent = np.dot(NumPersons,Price_per_100_g)
Price_in_Euro = Price_in_Cent / 100
Price_in_Euro

array([13.984, 11.907,  9.9  ,  9.745])

In [3]:
# The cross product of two vectors a and b is denoted by a × b.
# It's defined as:
# Cross Product Definition
# where n is a unit vector perpendicular to the plane containing a and b in the direction given by the right-hand rule.
# If either of the vectors being multiplied is zero or the vectors are parallel then their cross product is zero. More generally, the magnitude of the product equals the area of a parallelogram with the vectors as sides. If the vectors are perpendicular the parallelogram is a rectangle and the magnitude of the product is the product of their lengths.

x = np.array([0, 0, 1])
y = np.array([0, 1, 0])

np.cross(x, y)

array([-1,  0,  0])

In [4]:
np.cross(y, x)

array([1, 0, 0])