In [ ]:
# https://python-course.eu/numerical-programming/python-random-numbers-and-probability.php

In [5]:
import random
random_number = random.random()
print(random_number)

0.4289659509015663


In [11]:
from random import SystemRandom
crypto = SystemRandom()
print(crypto.random())

0.9255272870580922


In [12]:
import random

def random_list(n, secure=True):
    random_floats = []
    if secure:
        crypto = random.SystemRandom()
        random_float = crypto.random
    else:
        random_float = random.random
    for _ in range(n):
        random_floats.append(random_float())
    return random_floats

print(random_list(10, secure=False))

[0.06035820005475245, 0.09480014114809043, 0.5271929494348913, 0.3905924198748981, 0.04163108860224374, 0.13000993326730892, 0.025267676681949625, 0.9497980136711003, 0.40885535081352, 0.1282738635132854]


In [14]:
%%timeit
random_list(100)

89.6 µs ± 1.88 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [15]:
%%timeit
random_list(100, secure=False)

20.9 µs ± 8.19 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [16]:
crypto = random.SystemRandom()
[crypto.random() for _ in range(10)]

[0.470995611762119,
 0.4476015186952983,
 0.6311991812602924,
 0.5110836383832152,
 0.3625895981811498,
 0.49393126944768717,
 0.19877384576254753,
 0.6925684209139974,
 0.2743570561898887,
 0.4484424081151105]

In [17]:
%%timeit
[crypto.random() for _ in range(100)]

86.3 µs ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [18]:
import numpy as np

np.random.random(10)

array([0.44717692, 0.21771116, 0.76008929, 0.19236605, 0.56854754,
       0.76694118, 0.36132048, 0.945398  , 0.59095257, 0.09869703])

In [19]:
%%timeit
np.random.random(100)

3.58 µs ± 809 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [20]:
import numpy as np

list_of_random_floats = np.random.random(100)
sum_of_values = list_of_random_floats.sum()
print(sum_of_values)
normalized_values = list_of_random_floats / sum_of_values
print(normalized_values.sum())

49.396033702256815
1.0


In [21]:
from random import SystemRandom
sr = SystemRandom() # create an instance of the SystemRandom class
    

def generate_password(length, 
                      valid_chars=None):
    """ generate_password(length, check_char) -> password
        length: the length of the created password
        check_char: a Boolean function used to check the validity of a char
    """
    if valid_chars==None:
        valid_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        valid_chars += valid_chars.lower() + "0123456789"
    
    password = ""
    counter = 0
    while counter < length:
        rnum = sr.randint(0, 128)
        char = chr(rnum)
        if char in valid_chars:
            password += chr(rnum)
            counter += 1
    return password

print("Automatically generated password by Python: " + generate_password(15))

Automatically generated password by Python: rthh21A0Mp1o8JQ


In [22]:
import random

outcome = random.randint(1,6)
print(outcome)

4


In [23]:
import random

[ random.randint(1, 6) for _ in range(10) ]

[4, 4, 5, 4, 1, 1, 6, 6, 2, 3]

In [24]:
import numpy as np

outcome = np.random.randint(1, 7, size=10)
print(outcome)

[1 2 3 6 2 6 4 1 3 6]


In [25]:
import numpy as np

print(np.random.randint(1, 7))
print(np.random.randint(1, 7, size=1))
print(np.random.randint(1, 7, size=10))
print(np.random.randint(1, 7, size=(10,))) # the same as the previous one
print(np.random.randint(1, 7, size=(5, 4)))

4
[5]
[5 2 2 3 2 1 1 5 5 1]
[2 1 6 1 1 6 1 5 2 3]
[[4 1 6 6]
 [1 5 3 4]
 [6 4 1 3]
 [3 2 5 4]
 [6 3 1 6]]


In [26]:
import random

crypto = random.SystemRandom()

[ crypto.randint(1, 6) for _ in range(10) ]

[2, 3, 2, 5, 4, 2, 1, 1, 4, 5]

In [27]:
from random import choice

possible_destinations = ["Berlin", "Hamburg", "Munich", 
                         "Amsterdam", "London", "Paris", 
                         "Zurich", "Heidelberg", "Strasbourg", 
                         "Augsburg", "Milan", "Rome"]

print(choice(possible_destinations))

Zurich


In [28]:
from numpy.random import choice

print(choice(possible_destinations))

London


In [29]:
x1 = choice(possible_destinations, size=3)
print(x1)
x2 = choice(possible_destinations, size=(3, 4))
print(x2)

['Heidelberg' 'London' 'Amsterdam']
[['Amsterdam' 'Berlin' 'Rome' 'Munich']
 ['Zurich' 'Amsterdam' 'Augsburg' 'Amsterdam']
 ['Strasbourg' 'Milan' 'Milan' 'Rome']]


In [30]:
print(choice(possible_destinations, size=(3, 4), replace=False))

[['Heidelberg' 'Berlin' 'Augsburg' 'Paris']
 ['Rome' 'Amsterdam' 'Munich' 'Zurich']
 ['Strasbourg' 'Milan' 'London' 'Hamburg']]


In [31]:
import numpy as np

x = np.random.random_sample((3, 4))
print(x)

[[0.77682684 0.26216107 0.62511977 0.03833562]
 [0.56909128 0.14888742 0.32775864 0.52105353]
 [0.18983855 0.91632611 0.58242875 0.0453414 ]]


In [32]:
x = np.random.random_sample(7)
print(x)

y = np.random.random_sample((7,))
print(y)

[0.28505643 0.60332087 0.42603469 0.38399886 0.830609   0.61210207
 0.21535595]
[0.44549417 0.46918354 0.19701411 0.22185423 0.73485096 0.74510208
 0.18350143]


In [34]:
a = -3.4
b = 5.9

A = (b - a) * np.random.random_sample((3, 4)) + a
print(A)

[[ 2.18426573  1.44422356  5.3249435   0.0761163 ]
 [ 1.93166721  2.50436681 -1.31198938 -2.35503176]
 [-3.00880564  5.31864325  4.36167021  0.30877025]]


In [40]:
import random

print(random.sample(range(1, 50), 6))

[11, 17, 49, 39, 24, 41]
