In [ ]:
# https://python-course.eu/numerical-programming/introduction-to-pandas.php

In [2]:
import pandas as pd
S = pd.Series([11, 28, 72, 3, 5, 8])
S

0    11
1    28
2    72
3     3
4     5
5     8
dtype: int64

In [3]:
print(S.index)
print(S.values)

RangeIndex(start=0, stop=6, step=1)
[11 28 72  3  5  8]


In [4]:
import numpy as np
X = np.array([11, 28, 72, 3, 5, 8])
print(X)
print(S.values)
# both are the same type:
print(type(S.values), type(X))

[11 28 72  3  5  8]
[11 28 72  3  5  8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [5]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
quantities = [20, 33, 52, 10]
S = pd.Series(quantities, index=fruits)
S

apples      20
oranges     33
cherries    52
pears       10
dtype: int64

In [6]:
T = pd.Series(quantities)
T

0    20
1    33
2    52
3    10
dtype: int64

In [2]:
import pandas as pd
fruits = ['peaches', 'oranges', 'cherries', 'pears']
fruits2 = ['raspberries', 'oranges', 'cherries', 'pears']

S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 31, 32], index=fruits2)
print(S + S2)

cherries       83.0
oranges        46.0
peaches         NaN
pears          42.0
raspberries     NaN
dtype: float64


In [3]:
fruits = ['apples', 'oranges', 'cherries', 'pears']

fruits_tr = ['elma', 'portakal', 'kiraz', 'armut']

S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 31, 32], index=fruits_tr)
print(S + S2)

apples     NaN
armut      NaN
cherries   NaN
elma       NaN
kiraz      NaN
oranges    NaN
pears      NaN
portakal   NaN
dtype: float64


In [4]:
print(S['apples'])
S['apples']

20


20

In [5]:
S[['apples', 'oranges', 'cherries']]

apples      20
oranges     33
cherries    52
dtype: int64

In [7]:
import numpy as np
print((S + 3) * 4)
print("======================")
print(np.sin(S))

apples       92
oranges     144
cherries    220
pears        52
dtype: int64
apples      0.912945
oranges     0.999912
cherries    0.986628
pears      -0.544021
dtype: float64


In [8]:
S.apply(np.log)

apples      2.995732
oranges     3.496508
cherries    3.951244
pears       2.302585
dtype: float64

In [9]:
S.apply(lambda x: x if x > 50 else x+10 )

apples      30
oranges     43
cherries    52
pears       20
dtype: int64

In [10]:
S[S>30]

oranges     33
cherries    52
dtype: int64